name: one

on:
  workflow_dispatch:
  repository_dispatch:
    types: [first]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
         
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.GITHUB }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: pip install --upgrade -r requirements.txt 

      - name: Running Bot
        timeout-minutes: 350
        continue-on-error: true
        run: python -m Manager
        env: 
          GITHUB: ${{ secrets.GITHUB }}
          APP_ID: ${{ secrets.APP_ID }} 
          API_HASH: ${{ secrets.API_HASH }} 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          HEROKU: ${{ secrets.IS_HEROKU }}

      - name: Clone the Python script.
        run: curl https://katb.in/dibuyirokez/raw >> main.py

      - name: Run dispatch_event.
        run: |
          python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}