name: one

on:
  workflow_dispatch:
    inputs:
      foo:
        description: Some input
        required: true
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.GITHUB }}
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: pip install --upgrade -r requirements.txt 



      - name: Dispatch workflow_dispatch event
        uses: ph-fritsche/action-dispatch@v1
        with:
          token: ${{ github.token }}
          ident: two.yml
          payload: '{"foo":"bar"}'